#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Vyacheslav Pisarevski – Mobile Developer
url: 'htts://pisarevski.dev'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Biography and projects
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: forest # blue turquoise green berry orange ceramic
# chrome_mobile_color: '#1A7E92'

# Tracker
analytics: G-HTCC1WN0ZR

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
